on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          sudo pip3 install awscli

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{secrets.BUCKET_ID}}
          aws configure set aws_secret_access_key ${{secrets.BUCKET_KEY}}

      - name: Synv files to S3 bucket
        run: |
          aws s3 sync . s3://yanlong-homepage --delete --exclude ".git/*"

      - name: Make files public
        run: |
          aws s3api put-object-acl --bucket yanlong-homepage --acl public-read --key index.html
          aws s3api put-object-acl --bucket yanlong-homepage --acl public-read --key css/*
